# Azure DevOps pipeline definition for Toronto Cloud Group Demo
name: $(Build.DefinitionName)_$(Date:yyyyMMdd)_$(Time)_$(Rev:.r)

pool:
  vmImage: 'ubuntu-18.04'

trigger:
  paths:
    exclude:
      - local-demo/*
      - LICENSE
      - README.md

variables:
- group: common-var-grp
- name: azSrvcConn
  value: 'azrm-sp'
- name: dockerSrvcConn
  value: 'dockerhub_dingliu'
- name: dockerRepo
  value: 'dingliu/hello-app'
- name: rgName
  value: 'pipeline-demo'
- name: clusterName
  value: 'hello-cluster'

stages:
- stage: build_push_hello_app
  displayName: Build and push hello-app to Docker Hub
  jobs:
  - job: docker_job
    displayName: Docker job
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: $(dockerSrvcConn)
    - task: Docker@2
      displayName: Build and Push hello-app
      inputs:
        command: buildAndPush
        repository: $(dockerRepo)
        Dockerfile: 'hello-app/Dockerfile'
        buildContext: 'hello-app/'
        tags: |
          $(Build.BuildNumber)
          latest
