# Azure DevOps pipeline definition for Toronto Cloud Group Demo
name: $(Build.DefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'ubuntu-18.04'

trigger:
  paths:
    exclude:
      - local-demo/*
      - LICENSE
      - README.md

variables:
- group: common-var-grp
- name: azSrvcConn
  value: 'azrm-sp'
- name: dockerSrvcConn
  value: 'dockerhub_dingliu'
- name: dockerRepo
  value: 'dingliu/hello-app'
- name: rgName
  value: 'pipeline-demo'
- name: clusterName
  value: 'hello-cluster'

stages:
- stage: build-push-hello-app
  displayName: Build and push hello-app to Docker Hub
  jobs:
  - job: docker-job
    displayName: Docker job
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: $(dockerSrvcConn)
    - task: Docker@2
      displayName: Build and Push hello-app
      inputs:
        command: buildAndPush
        repository: $(dockerRepo)
        Dockerfile: 'hello-app/Dockerfile'
        buildContext: 'hello-app/'
        tags: |
          $(Build.BuildNumber)
          latest
- stage: deploy-aks-cluster
  displayName: AKS cluster deployment
  condition: succeeded()
  jobs:
  - job: arm-template
    displayName: ARM template deployment
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: ARM template deployment
      inputs:
        deploymentScope: 'Subscription'
        azureResourceManagerConnection: $(azSrvcConn)
        subscriptionId: $(subscriptionId)
        location: 'Canada Central'
        templateLocation: 'Linked artifact'
        csmFile: 'cluster-arm/template.jsonc'
        csmParametersFile: 'cluster-arm/parameters.jsonc'
        overrideParameters: '-rgName $(rgName) -clusterName $(clusterName)'
        deploymentMode: 'Incremental'
        deploymentName: $(Build.BuildNumber)
- stage: apply-k8s-manifests
  displayName: Apply Kubernetes manifests
  condition: succeeded()
  jobs:
  - job: k8s-manifests
    displayName: Kubernetes manifests
    steps:
    - template: kubectl-step.yml
      parameters:
        manifests:
        - "cluster-manifests/helloweb-deployment.yaml"
        - "cluster-manifests/helloweb-hpa.yaml"
        - "cluster-manifests/helloweb-service-static-ip.yaml"
        - "cluster-manifests/helloweb-ingress-static-ip.yaml"
