# Azure DevOps pipeline definition for Toronto Cloud Group Demo
name: $(Build.DefinitionName)_$(Date:yyyyMMdd)_$(Time:HH:mm:ss)_$(Rev:.r)

pool:
  vmImage: 'ubuntu-18.04'

trigger:
  paths:
    exclude:
      - local-demo/*
      - LICENSE
      - README.md

variables:
- group: common-var-grp
- name: azSrvcConn
  value: 'azrm-sp'
- name: dockerSrvcConn
  value: 'dockerhub_dingliu'
- name: dockerRepo
  value: 'dingliu/hello-app'
- name: rgName
  value: 'pipeline-demo'
- name: clusterName
  value: 'hello-cluster'

stages:
- stage: test_stage
  displayName: Test Stage
  jobs:
  - job: test_job
    displayName: Test job
    steps:
    - bash: |
        echo "Hello world"
